﻿
#ifndef RESOURCE_H
#define RESOURCE_H

#define IDD_MFC_START_DIALOG 101
#define IDR_MAINFRAME 128

#endif // RESOURCE_H

#define IDD_MFC_START_DIALOG 101
#define IDR_MAINFRAME 128

#define IDS_ABOUTBOX 103

#define IDC_BUTTON_RESET 1001
#define IDC_BUTTON_RANDOM_MOVE 1002
